#! /bin/sh

	## AUTOSTART ##
sxhkd &
setxkbmap it &
picom -cb --config ~/.config/picom.conf &
/home/jacopo/.config/polybar/launch.sh &
wal -R 


	## MONITORs WORKSPACES ##
bspc monitor -d 1 2 3


	## THEM GAPS ##
bspc config border_width         	2
bspc config window_gap          	15


	## SOURCE THE COLORS ##
. "${HOME}/.cache/wal/colors.sh"


	## SET BORDER COLORS ##
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"


	## WINDOWS RULES ##
bspc config split_ratio          	0.52
bspc config focus_follows_pointer	true
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true


	## SOFTWARE SPECIFIC RULES ##
