#! /bin/sh
sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         	2
bspc config window_gap          	15
bspc config normal_border_color		"#F5EEEB"
bspc config focused_border_color	"#F4BC87"

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true

bspc rule -a Chromium desktop='^1'
bspc rule -a Pavucontrol state=floating
bspc rule -a Spotify desktop='^3'
bspc rule -a Lutris desktop='^4'
bspc rule -a discord desktop='^4'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a Galculator state=floating
bspc rule -a Gimp desktop='^5'

## Autostart programs ##

picom -b --config $HOME/.config/picom/picom.conf &
feh --bg-scale $HOME/Immagini/Sfondi/wallhaven-vgd838.jpg &
killall dunst &
dunst &
$HOME/.config/polybar/launch.sh &
nm-applet &
sleep 2 &
blueman-applet &
