#! /bin/sh

sxhkd &
setxkbmap it &
picom -bc --config $HOME/.config/picom/picom.conf &
redshift &
feh --bg-scale $HOME/Immagini/Sfondi/wallhaven-dgrk83.jpg &
killall -q dunst 
dunst &
$HOME/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4

bspc config border_width         	2
bspc config window_gap          	15
bspc config normal_border_color		"#1A1C1E"
bspc config focused_border_color	"#B73838"

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true

bspc rule -a Chromium desktop='^1'
bspc rule -a Pavucontrol state=floating
bspc rule -a Spotify desktop='^3'
bspc rule -a Lutris desktop='^4' state=pseudo_tiled
