#!/usr/bin/env bash

# Brightness handler using brightnessctl

function cbright {
    brightnessctl i | grep '%' | awk -F'(' '{print $2}' | awk -F'%' '{print $1}'
}

function notify {
    brightness=`cbright`
    
    if [ "$brightness" = "0" ]; then
        icon_name="display-brightness-off-symbolic"
    else    
        if [  "$brightness" -lt "30" ]; then
            icon_name="display-brightness-low-symbolic"
        else
            if [ "$brightness" -lt "70" ]; then
                  icon_name="display-brightness-medium-symbolic"
            else
                if [ "$brightness" -lt "100" ]; then
                     icon_name="display-brightness-high-symbolic"
                else
                      icon_name="display-brightness-high-symbolic"
                fi
            fi
        fi
    fi

    dunstify -i "/home/jacopo/.icons/oomox-xresources/symbolic/status/$icon_name.svg" -t 3000 -r 123 "$brightness %"
}

case $1 in
    up)
	# +2%
	brightnessctl set 2%+ > /dev/null
	notify
	;;
    down)
    	# -2%
    	brightnessctl set 2%- > /dev/null
	notify
	;;
    optimal)
    	# Toggle optimal
	brightnessctl set 25% > /dev/null
    	notify
	;;
esac    
