#!/bin/bash

# Audio volume listener for polybar

function cvol {
    amixer -D pulse get Master | grep '%' | head -n 1 | awk -F'[' '{print $2}' | awk -F'%' '{print $1}'
}

function chkmute {
    amixer -D pulse get Master | grep '%' | grep -oE '[^ ]+$' | awk '{print $1; exit}'
}

function display {
    volume=`cvol`

    if [ "$volume" = "0" ]; then
        icon=""
    else
        if [  "$volume" -lt "20" ]; then
            icon=""
        else
            if [ "$volume" -lt "50" ]; then
                icon=""
            else
                if [ "$volume" -lt "70" ]; then
                    icon=""
                else
                    icon=""
                fi
            fi
        fi
    fi

    echo "$icon"
}

chk=`chkmute`
  if [ "$chk" = "[off]" ] ; then
    echo " Muto"
	else
	    display
	fi
